import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} text-center ` }>
        <h1 className="text-2xl font-bold pt-4">Dinossaurs Facts</h1>
        {children}
        </body>
    </html>
  )
}
